'use client'
import { useState, useEffect } from 'react'
import { getDocuments, getOpportunities, deleteDocument, deleteOpportunity, type GeneratedDocument, type SavedOpportunity } from '@/lib/storage'
import Card from '@/components/ui/Card'
import Badge from '@/components/ui/Badge'
import { Bookmark, FileText, ExternalLink, Trash2, Download, FileDown, Search } from 'lucide-react'
import toast from 'react-hot-toast'
import { formatDate } from '@/lib/utils'

export default function SavedPage() {
  const [documents, setDocuments] = useState<GeneratedDocument[]>([])
  const [savedOps, setSavedOps] = useState<SavedOpportunity[]>([])
  const [activeTab, setActiveTab] = useState<'documents' | 'opportunities'>('documents')
  const [search, setSearch] = useState('')

  useEffect(() => {
    setDocuments(getDocuments())
    setSavedOps(getOpportunities())
  }, [])

  const handleDeleteDoc = (id: string) => {
    deleteDocument(id)
    setDocuments(prev => prev.filter(d => d.id !== id))
    toast.success('Document deleted')
  }

  const handleDeleteOpp = (id: string) => {
    deleteOpportunity(id)
    setSavedOps(prev => prev.filter(o => o.id !== id))
    toast.success('Removed')
  }

  const downloadTxt = (doc: GeneratedDocument) => {
    const blob = new Blob([doc.content || ''], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${doc.title || 'document'}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const exportPDF = (doc: GeneratedDocument) => {
    const printWindow = window.open('', '_blank')
    if (!printWindow) { toast.error('Allow popups to export PDF'); return }
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${doc.title}</title>
          <style>
            body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #111; line-height: 1.6; }
            h1 { font-size: 18px; margin-bottom: 4px; }
            .meta { font-size: 12px; color: #666; margin-bottom: 24px; }
            pre { white-space: pre-wrap; font-family: Arial, sans-serif; font-size: 13px; }
            @media print { body { margin: 20px; } }
          </style>
        </head>
        <body>
          <h1>${doc.title}</h1>
          <div class="meta">Generated by Web3 Career Hub</div>
          <pre>${(doc.content || '').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
          <script>window.onload = () => { window.print(); }<\/script>
        </body>
      </html>
    `)
    printWindow.document.close()
  }

  const typeColors: Record<string, 'info' | 'success' | 'warning'> = { cv: 'info', resume: 'success', cover_letter: 'warning' }
  const typeLabels: Record<string, string> = { cv: 'CV', resume: 'Resume', cover_letter: 'Cover Letter' }

  const kw = search.toLowerCase()
  const filteredDocs = documents.filter(d => !kw || d.title?.toLowerCase().includes(kw) || d.job_title?.toLowerCase().includes(kw) || d.company_name?.toLowerCase().includes(kw))
  const filteredOps = savedOps.filter(o => !kw || o.title?.toLowerCase().includes(kw) || o.company?.toLowerCase().includes(kw))

  return (
    <div className="space-y-6 animate-fade-in">
      <div>
        <h1 className="text-2xl font-bold text-white">Saved Items</h1>
        <p className="text-[#8888aa] text-sm mt-1">Your generated documents and saved opportunities in one place</p>
      </div>

      <div className="flex flex-col md:flex-row gap-3 items-start md:items-center">
        <div className="flex gap-2">
          {(['documents', 'opportunities'] as const).map(tab => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-all capitalize ${
                activeTab === tab ? 'bg-[#6c63ff] text-white' : 'bg-[#1a1a2e] text-[#8888aa] hover:text-white border border-[#1e1e35]'
              }`}
            >
              {tab} {tab === 'documents' ? `(${documents.length})` : `(${savedOps.length})`}
            </button>
          ))}
        </div>
        <div className="relative flex-1 md:max-w-xs">
          <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#555577]" />
          <input
            className="w-full pl-9 pr-3 py-2 rounded-lg bg-[#12121f] border border-[#1e1e35] text-white text-sm placeholder:text-[#555577] focus:outline-none focus:border-[#6c63ff]"
            placeholder="Search saved items..."
            value={search}
            onChange={e => setSearch(e.target.value)}
          />
        </div>
      </div>

      {activeTab === 'documents' ? (
        filteredDocs.length === 0 ? (
          <Card className="text-center py-12">
            <FileText size={32} className="text-[#555577] mx-auto mb-3" />
            <p className="text-sm font-medium text-white">{search ? 'No results' : 'No documents saved'}</p>
            <p className="text-xs text-[#555577] mt-1">{search ? 'Try a different search' : 'Generate and save CVs, resumes, or cover letters'}</p>
          </Card>
        ) : (
          <div className="space-y-3">
            {filteredDocs.map(doc => (
              <Card key={doc.id} className="group">
                <div className="flex items-center justify-between gap-4">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <h3 className="font-medium text-white text-sm truncate">{doc.title}</h3>
                      <Badge variant={typeColors[doc.type] || 'default'}>{typeLabels[doc.type] || doc.type}</Badge>
                      {doc.ai_score != null && (
                        <span className={`text-xs ${doc.ai_score <= 30 ? 'text-green-400' : 'text-yellow-400'}`}>
                          {doc.ai_score}% AI score
                        </span>
                      )}
                    </div>
                    {doc.job_title && (
                      <p className="text-xs text-[#8888aa] mt-0.5">Target: {doc.job_title}{doc.company_name ? ` @ ${doc.company_name}` : ''}</p>
                    )}
                    <p className="text-xs text-[#555577] mt-0.5">Saved {formatDate(doc.created_at)}</p>
                  </div>
                  <div className="flex gap-2 shrink-0">
                    <button onClick={() => exportPDF(doc)} title="Export as PDF"
                      className="p-1.5 rounded-lg bg-[#1a1a2e] text-[#8888aa] hover:text-[#6c63ff] border border-[#1e1e35] transition-colors">
                      <FileDown size={13} />
                    </button>
                    <button onClick={() => downloadTxt(doc)} title="Download as TXT"
                      className="p-1.5 rounded-lg bg-[#1a1a2e] text-[#8888aa] hover:text-white border border-[#1e1e35] transition-colors">
                      <Download size={13} />
                    </button>
                    <button onClick={() => handleDeleteDoc(doc.id)}
                      className="p-1.5 rounded-lg bg-[#1a1a2e] text-[#555577] hover:text-red-400 border border-[#1e1e35] transition-colors opacity-0 group-hover:opacity-100">
                      <Trash2 size={13} />
                    </button>
                  </div>
                </div>
                <div className="mt-3 bg-[#0f0f1a] rounded-lg p-3 max-h-24 overflow-hidden relative">
                  <pre className="text-xs text-[#555577] whitespace-pre-wrap font-sans">{(doc.content || '').slice(0, 200)}...</pre>
                  <div className="absolute bottom-0 left-0 right-0 h-8 bg-gradient-to-t from-[#0f0f1a]" />
                </div>
              </Card>
            ))}
          </div>
        )
      ) : (
        filteredOps.length === 0 ? (
          <Card className="text-center py-12">
            <Bookmark size={32} className="text-[#555577] mx-auto mb-3" />
            <p className="text-sm font-medium text-white">{search ? 'No results' : 'No saved opportunities'}</p>
            <p className="text-xs text-[#555577] mt-1">{search ? 'Try a different search' : 'Save jobs and opportunities from the Jobs tab'}</p>
          </Card>
        ) : (
          <div className="space-y-3">
            {filteredOps.map(opp => (
              <Card key={opp.id} className="group">
                <div className="flex items-center justify-between gap-4">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <h3 className="font-medium text-white text-sm truncate">{opp.title}</h3>
                      <Badge variant="default" className="capitalize">{opp.opportunity_type}</Badge>
                      <Badge variant="info" className="capitalize">{opp.status}</Badge>
                    </div>
                    <p className="text-xs text-[#8888aa] mt-0.5">{opp.company} • Saved {formatDate(opp.created_at)}</p>
                  </div>
                  <div className="flex gap-2 shrink-0">
                    <a href={opp.url} target="_blank" rel="noopener noreferrer"
                      className="p-1.5 rounded-lg bg-[#1a1a2e] text-[#8888aa] hover:text-white border border-[#1e1e35] transition-colors">
                      <ExternalLink size={13} />
                    </a>
                    <button onClick={() => handleDeleteOpp(opp.id)}
                      className="p-1.5 rounded-lg bg-[#1a1a2e] text-[#555577] hover:text-red-400 border border-[#1e1e35] transition-colors opacity-0 group-hover:opacity-100">
                      <Trash2 size={13} />
                    </button>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        )
      )}
    </div>
  )
}
